### ISSUE TITLE
Could this be used in an Electron project?

### ISSUE THREAD

**Issue by altinselimi** [evyatarmeged/Humanoid#1]
Hi, 

I'm in dire need of a cloud-flare bypass library, and currently there aren't many out there. This seems to be a good candidate, but I would like to know if it would be possible to use it inside an Electron desktop application.

Thanks !

**Comment by evyatarmeged** [comment]
HI @altinselimi,

I don't see why not. Electron supports Node.js libraries and this one should be no different.
I did, however, got some trouble lately in bypassing Anti-DDoS pages but the challenge seemed to stay the same. Is this true for you as well? are you able to bypass CF successfully?
