### ISSUE TITLE
Error when installing with npm 

### ISSUE THREAD

**Issue by 888iee** [evyatarmeged/Humanoid#7]
Hi, 
I get an error when running npm i humanoid-js.
[npm cli error](https://pastebin.com/arwY7sGN)
and I also have a [log file](https://pastebin.com/4et3STN9)

**Comment by krid-sdnera** [comment]
The error you are encountering is due to a dependency of Humanoid.

As per the error message, try installing Visual Studio & its  "Desktop development with C++" option

```
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
```

Let us know if you still have issues after that.

**Comment by 888iee** [comment]
This solved my issue. I only thought thie error message is weird because I didn't thought of having c++ dependencies.
Anyways thank you very much!
